"""B1 数据入库 —— 将离线产物写入 MySQL 和 Qdrant。"""

from __future__ import annotations

import json
from pathlib import Path

from food_agent_v2.core.paths import CLEANED_DIR


def generate_mysql_seed() -> str:
    """生成 MySQL 种子数据 SQL。"""
    sql_parts = ["-- V2 seed data generated by B1\n"]
    line_count = 0

    # recipes
    recipes_path = CLEANED_DIR / "clean_recipes.jsonl"
    if recipes_path.exists():
        with recipes_path.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                r = json.loads(line)
                name = _escape_sql(r["名称"])
                ingredients = _escape_sql(r.get("食材清单", ""))
                steps = _escape_sql(r.get("烹饪步骤", ""))
                labels = _escape_sql(r.get("label", ""))
                sql_parts.append(
                    f"INSERT INTO recipes (recipe_id, name, ingredients_raw, steps_raw, labels_raw) "
                    f"VALUES ({r['recipe_id']}, '{name}', '{ingredients}', '{steps}', '{labels}') "
                    f"ON DUPLICATE KEY UPDATE name=VALUES(name);"
                )
                line_count += 1

    # ingredients
    ing_path = CLEANED_DIR / "ingredient_registry.jsonl"
    if ing_path.exists():
        with ing_path.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                r = json.loads(line)
                name = _escape_sql(r["name_canonical"])
                edible = 1 if r.get("is_edible", True) else 0
                pantry = 1 if r.get("is_basic_pantry", False) else 0
                sql_parts.append(
                    f"INSERT INTO ingredients (ingredient_id, name_canonical, is_edible, is_basic_pantry) "
                    f"VALUES ({r['ingredient_id']}, '{name}', {edible}, {pantry}) "
                    f"ON DUPLICATE KEY UPDATE name_canonical=VALUES(name_canonical);"
                )
                line_count += 1

    # health relations
    hr_path = CLEANED_DIR / "health_relations.jsonl"
    if hr_path.exists():
        with hr_path.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                r = json.loads(line)
                code = _escape_sql(r["constraint_code"])
                status = r.get("review_status", "approved")
                hard = 1 if r.get("hard_filter", True) else 0
                evidence = _escape_sql(r.get("evidence_ref", ""))
                sql_parts.append(
                    f"INSERT INTO health_relations (constraint_code, ingredient_id, review_status, hard_filter, evidence_ref) "
                    f"VALUES ('{code}', {r['ingredient_id']}, '{status}', {hard}, '{evidence}') "
                    f"ON DUPLICATE KEY UPDATE review_status=VALUES(review_status);"
                )
                line_count += 1

    # nutrition profiles
    np_path = CLEANED_DIR / "nutrition_profiles.jsonl"
    if np_path.exists():
        with np_path.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                r = json.loads(line)
                nutrients = _escape_sql(json.dumps(r.get("nutrient_values", {}), ensure_ascii=False))
                sql_parts.append(
                    f"INSERT INTO nutrition_profiles (recipe_id, match_method, confidence, coverage_ratio, nutrient_values) "
                    f"VALUES ({r['recipe_id']}, '{r.get('match_method', 'partial')}', "
                    f"'{r.get('confidence', 'low')}', {r.get('coverage_ratio', 0)}, '{nutrients}') "
                    f"ON DUPLICATE KEY UPDATE confidence=VALUES(confidence);"
                )

    # user profiles
    users_path = CLEANED_DIR.parent / "cleaned" / "user_profiles.jsonl"
    if users_path.exists():
        with users_path.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                u = json.loads(line)
                uid = u["user_id"]
                gender = _escape_sql(u.get("gender", "") or "")
                age = u.get("age", "NULL") or "NULL"
                allergies = _escape_sql(json.dumps(u.get("allergies", []), ensure_ascii=False))
                goals = _escape_sql(json.dumps(u.get("health_goals", []), ensure_ascii=False))
                diseases = _escape_sql(json.dumps(u.get("diseases", []), ensure_ascii=False))
                taboos = _escape_sql(json.dumps(u.get("taboo_ingredients", []), ensure_ascii=False))
                metrics = _escape_sql(json.dumps(u.get("health_metrics", {}), ensure_ascii=False))
                prefs = _escape_sql(json.dumps(u.get("dietary_preferences", []), ensure_ascii=False))
                sql_parts.append(
                    f"INSERT INTO user_profiles (user_id, gender, age, dietary_preferences, allergies, health_goals, diseases, taboo_ingredients, health_metrics) "
                    f"VALUES ({uid}, '{gender}', {age}, '{prefs}', '{allergies}', '{goals}', '{diseases}', '{taboos}', '{metrics}') "
                    f"ON DUPLICATE KEY UPDATE health_metrics=VALUES(health_metrics);"
                )

    sql_text = "\n".join(sql_parts)
    output_path = CLEANED_DIR / "seed_data.sql"
    output_path.write_text(sql_text, encoding="utf-8")
    return str(output_path)


def generate_qdrant_payloads() -> str:
    """生成 Qdrant 向量索引的 payload 文件。"""
    rag_path = CLEANED_DIR / "rag_documents.jsonl"
    if not rag_path.exists():
        return ""

    payloads = []
    with rag_path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            doc = json.loads(line)
            payloads.append({
                "id": doc["recipe_id"],
                "document_id": doc["document_id"],
                "name": doc["name"],
                "searchable_text": doc["searchable_text"],
                "searchable_fields": doc.get("searchable_fields", {}),
                "step_summary": doc.get("step_summary"),
            })

    output_path = CLEANED_DIR / "qdrant_payloads.jsonl"
    with output_path.open("w", encoding="utf-8") as f:
        for p in payloads:
            f.write(json.dumps(p, ensure_ascii=False) + "\n")

    return str(output_path)


def _escape_sql(value: str) -> str:
    """转义 SQL 字符串。"""
    return value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


if __name__ == "__main__":
    sql_path = generate_mysql_seed()
    print(f"MySQL seed: {sql_path}")
    qdrant_path = generate_qdrant_payloads()
    print(f"Qdrant payloads: {qdrant_path}")
